version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x"

[[transformers]]
name = "ruff"
enabled = true

[[transformers]]
name = "test-coverage"
enabled = true
